[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"

[dev.environment]
  NODE_VERSION = "18"

# Disable Git submodule initialization
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[functions]
  node_bundler = "esbuild"
